.PHONY : run

run:
	$(MAKE) runsniper-ooo-v runsniper-vio-v runsniper-ino-v

APP_NAME=rvv_memcpy

SOURCE_FILES += rvv_memcpy.c

include ../microbenches.mk
include ../../scripts/compile.mk
include ../../scripts/runspike.mk
