.PHONY : run

run:
	$(MAKE) runsniper-ooo-v runsniper-vio-v runsniper-ino-v

SOURCE_FILES += rvv_strlen.c

APP_NAME = rvv_strlen

include ../microbenches.mk
include ../../scripts/compile.mk
include ../../scripts/runspike.mk
