.PHONY : run

run:
	$(MAKE) runsniper-ooo-v runsniper-vio-v runsniper-ino-v

SOURCE_FILES += main.c

APP_NAME = memcpy_scalar

include ../microbenches.mk
include ../../scripts/compile.mk
include ../../scripts/runspike.mk
