.PHONY : run

run:
	$(MAKE) runsniper-ooo-v runsniper-vio-v runsniper-ino-v

SOURCE_FILES = rvv_strncpy.c

APP_NAME = rvv_strncpy

include ../microbenches.mk
include ../../scripts/compile.mk
include ../../scripts/runspike.mk
