RISCV_GCC = riscv64-unknown-elf-gcc

SOURCE_FILES += rvv_gather_scatter_e16.c

APP_NAME = rvv_gather_scatter_e16
PK =  # this test case doesn't use PK

include ../microbenches.mk
include ../../scripts/compile.mk
include ../../scripts/runspike.mk
